---
title: Cyber Policy Ambassador/Translator
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
repository: beauwoods/beauwoods.github.io
name: Beau Woods
website: beauwoods.com
social-network-links:
  github: beauwoods
  twitter: beauwoods
  reddit: beauwoods
  linkedin: beauwoods
  orcid: 0000-0001-6109-1434
gtm: GTM-56D6KN8
footer_show_references: true
remote_theme: beauwoods/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- lib/
- scripts/
- docker-compose.yml
